use std::fs;
use std::path::Path;

fn main() {
  // 禁用 tauri-build 的默认 app manifest（common-controls v6），
  // 改由下方统一通过链接参数嵌入，确保 bin 与测试目标行为一致。
  tauri_build::try_build(
    tauri_build::Attributes::new()
      .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest()),
  )
  .expect("failed to run tauri-build");

  // workaround：tauri-build 默认仅给 bin 目标嵌入 Windows manifest（.res 方式），
  // 测试 exe 一旦链接 tauri 的 WinRT/GUI 代码路径（如 tauri-specta 收集全部命令），
  // 缺少 common-controls v6 激活上下文会在加载时 STATUS_ENTRYPOINT_NOT_FOUND (0xc0000139)。
  // 参考 tauri 官方示例：https://github.com/tauri-apps/tauri/pull/4383#issuecomment-1212221864
  let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
  let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
  if target_os == "windows" && target_env == "msvc" {
    embed_manifest();
  }

  generate_i18n();
}

fn embed_manifest() {
  let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("windows-app-manifest.xml");
  println!("cargo:rerun-if-changed={}", manifest.display());
  println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
  println!(
    "cargo:rustc-link-arg=/MANIFESTINPUT:{}",
    manifest.to_str().unwrap()
  );
}

// ─────────────────────────────────────────────────────────────────
// i18n 字典生成：单一来源 = src/i18n/*.ts（前端字典），
// build.rs 在编译期解析并生成 Rust 静态表，供 src/i18n.rs include。
// 任何键/文案的增删改只需编辑 TS 文件，两侧自动保持一致。
// ─────────────────────────────────────────────────────────────────

fn generate_i18n() {
  let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
  let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/i18n");
  let zh_path = src_dir.join("zh-CN.ts");
  let en_path = src_dir.join("en-US.ts");
  println!("cargo:rerun-if-changed={}", zh_path.display());
  println!("cargo:rerun-if-changed={}", en_path.display());

  let zh = parse_ts_dict(&zh_path);
  let en = parse_ts_dict(&en_path);

  let mut out = String::from(
    "// @generated by build.rs from ../src/i18n/zh-CN.ts and en-US.ts — DO NOT EDIT.\n\
     // 单一来源：前端 TS 字典。修改文案请编辑 src/i18n/*.ts。\n\n",
  );
  out.push_str("pub(crate) static ZH_CN_ENTRIES: &[(&str, &str)] = &[\n");
  for (k, v) in &zh {
    out.push_str(&format!("    ({:?}, {:?}),\n", k, v));
  }
  out.push_str("];\n\n");
  out.push_str("pub(crate) static EN_US_ENTRIES: &[(&str, &str)] = &[\n");
  for (k, v) in &en {
    out.push_str(&format!("    ({:?}, {:?}),\n", k, v));
  }
  out.push_str("];\n");

  let dest = Path::new(&out_dir).join("i18n_generated.rs");
  fs::write(&dest, out).expect("failed to write i18n_generated.rs");
}

/// 解析 TS 字典文件（`export default { 'key': 'value', ... }`），按 key 排序返回。
fn parse_ts_dict(path: &Path) -> Vec<(String, String)> {
  let src = fs::read_to_string(path)
    .unwrap_or_else(|e| panic!("failed to read i18n dict {}: {}", path.display(), e));
  let mut entries = Vec::new();
  for line in src.lines() {
    let t = line.trim();
    if !t.starts_with('\'') {
      continue;
    }
    let Some((key, rest)) = parse_single_quoted(t) else { continue };
    let Some(rest) = rest.trim_start().strip_prefix(':') else { continue };
    let rest = rest.trim_start();
    if !rest.starts_with('\'') {
      continue;
    }
    let Some((value, _)) = parse_single_quoted(rest) else { continue };
    entries.push((key, value));
  }
  entries.sort();
  entries
}

/// 解析以单引号开头的字符串字面量，返回 (内容, 剩余部分)。
/// 支持 TS 常见转义：\\ \' \n \t \r \0。
fn parse_single_quoted(s: &str) -> Option<(String, &str)> {
  let bytes = s.as_bytes();
  if bytes.first() != Some(&b'\'') {
    return None;
  }
  let mut i = 1;
  let mut out = String::new();
  while i < bytes.len() {
    let c = bytes[i];
    if c == b'\\' {
      if i + 1 >= bytes.len() {
        return None;
      }
      let e = bytes[i + 1];
      out.push(match e {
        b'\\' => '\\',
        b'\'' => '\'',
        b'n' => '\n',
        b't' => '\t',
        b'r' => '\r',
        b'0' => '\0',
        other => other as char,
      });
      i += 2;
    } else if c == b'\'' {
      return Some((out, &s[i + 1..]));
    } else {
      let len = utf8_len(c);
      out.push_str(&s[i..i + len]);
      i += len;
    }
  }
  None
}

fn utf8_len(b: u8) -> usize {
  if b < 0x80 {
    1
  } else if b >> 5 == 0b110 {
    2
  } else if b >> 4 == 0b1110 {
    3
  } else {
    4
  }
}
