[package]
name = "relwatch"
version = "1.0.0"
description = "RelWatch - Monitor GitHub releases"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.0", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-notification = "2"
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
rusqlite = { version = "0.39", features = ["bundled"] }
reqwest = { version = "0.13", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "6"
aes-gcm = "0.10"
sha2 = "0.11"
rand = "0.9"
base64 = "0.22"
hostname = "0.4"
tauri-winrt-notification = "0.7"
windows = { version = "0.62", features = ["Win32_System_Com"] }
tauri-plugin-single-instance = "2.4.2"
tauri-plugin-dialog = "2"
sys-locale = "0.3"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
strip = true
