/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	addSource: (sourceType: string, owner: string, repo: string, config: string | null) => __TAURI_INVOKE<number>("add_source", { sourceType, owner, repo, config }),
	removeSource: (id: number) => __TAURI_INVOKE<null>("remove_source", { id }),
	updateSource: (id: number, enabled: boolean, pollIntervalMinutes: number, muted: boolean | null, config: string | null) => __TAURI_INVOKE<null>("update_source", { id, enabled, pollIntervalMinutes, muted, config }),
	listSources: () => __TAURI_INVOKE<Source[]>("list_sources"),
	getReleases: () => __TAURI_INVOKE<ReleaseInfo[]>("get_releases"),
	setNotificationState: (releaseId: number, status: string, snoozeMinutes: number | null) => __TAURI_INVOKE<null>("set_notification_state", { releaseId, status, snoozeMinutes }),
	deleteRelease: (releaseId: number) => __TAURI_INVOKE<null>("delete_release", { releaseId }),
	/**
	 *  对单条 release 触发 AI 全文翻译。
	 *  用于用户在「原文」视图右键手动请求翻译旧 release 的场景。
	 *  仅在 AI 已启用且已配置 API key 时生效；若该 release 已有译文则直接返回。
	 */
	translateRelease: (releaseId: number) => __TAURI_INVOKE<null>("translate_release", { releaseId }),
	clearLogs: () => __TAURI_INVOKE<null>("clear_logs"),
	triggerPoll: () => __TAURI_INVOKE<PollResult>("trigger_poll"),
	checkSingleSource: (id: number) => __TAURI_INVOKE<PollResult>("check_single_source", { id }),
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	updateSettings: (payload: UpdateSettingsPayload) => __TAURI_INVOKE<null>("update_settings", { payload }),
	getPollCountdown: () => __TAURI_INVOKE<number>("get_poll_countdown"),
	setDeepseekApiKey: (apiKey: string) => __TAURI_INVOKE<null>("set_deepseek_api_key", { apiKey }),
	setGithubToken: (token: string) => __TAURI_INVOKE<null>("set_github_token", { token }),
	setYoutubeApiKey: (apiKey: string) => __TAURI_INVOKE<null>("set_youtube_api_key", { apiKey }),
	setBilibiliCookie: (cookie: string) => __TAURI_INVOKE<null>("set_bilibili_cookie", { cookie }),
	/**
	 *  判断 base_url 是否为 DeepSeek 官方域名（供前端保存/测试连接前二次确认，
	 *  审计建议 #1）。返回 bool，不阻止配置。
	 */
	isOfficialDeepseekBaseUrl: (baseUrl: string) => __TAURI_INVOKE<boolean>("is_official_deepseek_base_url", { baseUrl }),
	/**
	 *  从登录 WebView 读取 SESSDATA，验证有效后加密存储。
	 * 
	 *  - `Ok(true)`：读取并保存成功（前端应关闭登录窗口）
	 *  - `Err(err.bili_login_not_logged_in)`：窗口在但尚未登录（前端继续轮询）
	 *  - `Err(err.bili_login_window_missing)`：窗口已关闭（前端停止轮询）
	 *  - 其它 Err：读取/验证失败（前端提示）
	 */
	readBilibiliLoginCookie: (windowLabel: string) => __TAURI_INVOKE<boolean>("read_bilibili_login_cookie", { windowLabel }),
	/**  关闭登录窗口（前端在登录成功或用户放弃时调用）。 */
	closeBilibiliLoginWindow: (windowLabel: string) => __TAURI_INVOKE<null>("close_bilibili_login_window", { windowLabel }),
	testDeepseekConnection: (payload: {
	model: string | null,
	baseUrl: string | null,
	apiKey: string | null,
	proxyBypass: boolean | null,
	proxyUrl: string | null,
	proxyMode: string | null,
} | null) => __TAURI_INVOKE<string>("test_deepseek_connection", { payload }),
	searchLogs: (keyword: string, page: number, pageSize: number, level: string | null) => __TAURI_INVOKE<LogSearchResult>("search_logs", { keyword, page, pageSize, level }),
	exportBackup: () => __TAURI_INVOKE<string>("export_backup"),
	importBackup: () => __TAURI_INVOKE<null>("import_backup"),
	/**
	 *  将主窗口隐藏到系统托盘
	 * 
	 *  由前端的 Escape 逐层退出链最后一层触发。仅在用户开启了
	 *  `minimize_to_tray` 设置时才会被调用。
	 */
	hideToTray: () => __TAURI_INVOKE<null>("hide_to_tray"),
	/**
	 *  下载任意 http(s) URL 的原始字节并返回给前端。
	 *  前端复制图片时走 Rust 端下载：绕过 webview CORS 限制，并自动继承应用的代理设置。
	 *  返回 `Vec<u8>`，IPC 序列化为 number[]。
	 */
	fetchUrlBytes: (url: string) => __TAURI_INVOKE<number[]>("fetch_url_bytes", { url }),
	/**
	 *  写入文本到系统剪贴板。
	 *  前端 navigator.clipboard 依赖文档焦点/用户激活，在右键菜单等场景不可靠，
	 *  统一走 Rust 端写入。
	 */
	setClipboardText: (text: string) => __TAURI_INVOKE<null>("set_clipboard_text", { text }),
	/**
	 *  写入图片到系统剪贴板。`bytes` 为 PNG 编码字节（前端已用 canvas 统一转码），
	 *  这里解码为 RGBA 后交给 arboard（由它生成 Windows 需要的 DIBV5/PNG 格式）。
	 */
	setClipboardImage: (bytes: number[]) => __TAURI_INVOKE<null>("set_clipboard_image", { bytes }),
	/**
	 *  批量记录功能按钮点击统计。
	 *  内部校验诊断开关（enable_usage_stats）：关闭时静默丢弃，不做任何写入。
	 */
	recordUsage: (events: ([string, number])[]) => __TAURI_INVOKE<null>("record_usage", { events }),
	/**
	 *  查询使用统计（按累计次数降序）。仅开发者工具调用，不进入任何用户 UI。
	 *  `days` 提供时仅返回最近 N 天的数据（趋势窗口）。
	 */
	getUsageStats: (days: number | null) => __TAURI_INVOKE<UsageStatRow[]>("get_usage_stats", { days }),
	/**  清空全部使用统计。 */
	clearUsageStats: () => __TAURI_INVOKE<null>("clear_usage_stats"),
};

/** Events */
export const events = {
	navigate: makeEvent<Navigate>("navigate"),
	pollCompleted: makeEvent<PollCompleted>("poll-completed"),
	releaseStateChanged: makeEvent<ReleaseStateChanged>("release-state-changed"),
	sourceAutoDisabled: makeEvent<SourceAutoDisabled>("source-auto-disabled"),
};

/* Types */
export type AppSettings = {
	poll_interval_minutes: number,
	proxy_url: string,
	proxy_mode: string,
	auto_start: boolean,
	minimize_to_tray: boolean,
	log_retention_days: number,
	deepseek_enabled: boolean,
	deepseek_model: string,
	deepseek_base_url: string,
	deepseek_api_key_set: boolean,
	deepseek_proxy_bypass: boolean,
	deepseek_prompt: string,
	deepseek_min_importance: string,
	deepseek_translate_release: boolean,
	check_prereleases: boolean,
	fetch_history: boolean,
	fetch_history_count: number,
	language: string,
	theme: string,
	show_source_type_icons: boolean,
	enable_usage_stats: boolean,
	github_token_set: boolean,
	youtube_api_key_set: boolean,
	bilibili_cookie_set: boolean,
};

export type LogEntry = {
	id: number,
	level: string,
	message: string,
	created_at: string,
	message_key: string | null,
	message_args: string | null,
	rendered_message: string | null,
};

export type LogSearchResult = {
	entries: LogEntry[],
	total: number,
	page: number,
	page_size: number,
};

/**  托盘菜单请求前端切换标签页，payload 为目标标签名。 */
export type Navigate = string;

/**  一次轮询完成（手动或定时），前端据此刷新列表与倒计时。 */
export type PollCompleted = null;

export type PollResult = {
	new_releases: ReleaseInfo[],
};

export type ReleaseInfo = {
	id: number,
	source_id: number,
	source_type: string,
	owner: string,
	repo: string,
	tag_name: string,
	release_name: string,
	html_url: string,
	published_at: string,
	prerelease: boolean,
	body: string | null,
	detected_at: string,
	notification_status: string,
	snooze_until: string | null,
	ai_summary: string | null,
	ai_importance: string | null,
	body_translated: string | null,
	extra_metadata: string | null,
	/**  所属源的描述（YouTube 源存频道名），前端用于展示可读名称。 */
	source_description: string | null,
};

/**  release 状态变更（新增/已读/忽略/删除等），payload 为 release id。 */
export type ReleaseStateChanged = number;

export type Source = {
	id: number,
	source_type: string,
	owner: string,
	repo: string,
	poll_interval_minutes: number,
	enabled: boolean,
	last_checked_at: string | null,
	last_check_status: string,
	last_check_message: string | null,
	consecutive_failures: number,
	last_new_count: number,
	muted: boolean,
	created_at: string,
	updated_at: string,
	description: string | null,
	/**  源级附加配置（JSON）。目前用于 YouTube 订阅内容类型（视频/直播/帖子）。 */
	config: string | null,
};

/**  源因连续失败被自动禁用，payload 携带源信息供前端提示。 */
export type SourceAutoDisabled = {
	owner: string,
	repo: string,
	id: number,
	failures: number,
};

/**
 *  测试连接的可选覆盖参数：前端把表单当前值（含未保存修改）传入，
 *  留空的项回退到已保存配置，实现"先试后存"。
 */
export type TestDeepseekPayload = {
	model: string | null,
	baseUrl: string | null,
	apiKey: string | null,
	proxyBypass: boolean | null,
	proxyUrl: string | null,
	proxyMode: string | null,
};

/**  仅用于 `update_settings` 接收前端参数 */
export type UpdateSettingsPayload = {
	pollIntervalMinutes: number,
	proxyUrl: string,
	proxyMode: string,
	autoStart: boolean,
	minimizeToTray: boolean,
	logRetentionDays: number,
	deepseekEnabled: boolean,
	deepseekModel: string,
	deepseekBaseUrl: string,
	deepseekProxyBypass: boolean,
	deepseekPrompt: string,
	deepseekMinImportance: string,
	deepseekTranslateRelease: boolean,
	checkPrereleases: boolean,
	fetchHistory: boolean,
	fetchHistoryCount: number,
	language: string,
	theme: string,
	showSourceTypeIcons: boolean,
	enableUsageStats: boolean,
};

/**  单日计数（按本地时区 YYYY-MM-DD 分桶）。 */
export type UsageDaily = {
	day: string,
	count: number,
};

/**  单个事件的聚合统计行：total_count 为累计次数（SUM），daily 为按天趋势。 */
export type UsageStatRow = {
	key: string,
	total_count: number,
	last_day: string,
	daily: UsageDaily[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

