/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	addSource: (sourceType: string, owner: string, repo: string, config: string | null) => __TAURI_INVOKE<number>("add_source", { sourceType, owner, repo, config }),
	listSourceTypes: () => __TAURI_INVOKE<SourceTypeInfo[]>("list_source_types"),
	removeSource: (id: number) => __TAURI_INVOKE<null>("remove_source", { id }),
	updateSource: (id: number, enabled: boolean, pollIntervalMinutes: number, muted: boolean | null, config: string | null) => __TAURI_INVOKE<null>("update_source", { id, enabled, pollIntervalMinutes, muted, config }),
	listSources: () => __TAURI_INVOKE<Source[]>("list_sources"),
	getReleases: () => __TAURI_INVOKE<ReleaseInfo[]>("get_releases"),
	setNotificationState: (releaseId: number, status: string, snoozeMinutes: number | null) => __TAURI_INVOKE<null>("set_notification_state", { releaseId, status, snoozeMinutes }),
	deleteRelease: (releaseId: number) => __TAURI_INVOKE<null>("delete_release", { releaseId }),
	/**
	 *  对单条 release 触发 AI 全文翻译。
	 *  用于用户在「原文」视图右键手动请求翻译旧 release 的场景。
	 *  仅在 AI 已启用且已配置 API key 时生效；若该 release 已有译文则直接返回。
	 */
	translateRelease: (releaseId: number) => __TAURI_INVOKE<null>("translate_release", { releaseId }),
	clearLogs: () => __TAURI_INVOKE<null>("clear_logs"),
	triggerPoll: () => __TAURI_INVOKE<PollResult>("trigger_poll"),
	checkSingleSource: (id: number) => __TAURI_INVOKE<PollResult>("check_single_source", { id }),
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	/**
	 *  设置读写共用 `AppSettings`（types.rs）：不再维护第二份与 AppSettings
	 *  逐字段重复的 payload 结构，新增设置项少一处同步点。
	 */
	updateSettings: (payload: AppSettings) => __TAURI_INVOKE<null>("update_settings", { payload }),
	getPollCountdown: () => __TAURI_INVOKE<number>("get_poll_countdown"),
	/**
	 *  设置/更新单个加密凭据：空值清除，非空值加密存储。
	 *  `kind` 必须命中 `CREDENTIAL_KINDS` 注册表，未知 kind 返回错误（不静默）。
	 */
	setCredential: (kind: string, value: string) => __TAURI_INVOKE<null>("set_credential", { kind, value }),
	/**
	 *  从登录 WebView 读取 SESSDATA，验证有效后加密存储。
	 * 
	 *  - `Ok(true)`：读取并保存成功（前端应关闭登录窗口）
	 *  - `Err(err.bili_login_not_logged_in)`：窗口在但尚未登录（前端继续轮询）
	 *  - `Err(err.bili_login_window_missing)`：窗口已关闭（前端停止轮询）
	 *  - 其它 Err：读取/验证失败（前端提示）
	 */
	readBilibiliLoginCookie: (windowLabel: string) => __TAURI_INVOKE<boolean>("read_bilibili_login_cookie", { windowLabel }),
	/**  关闭登录窗口（前端在登录成功或用户放弃时调用）。 */
	closeBilibiliLoginWindow: (windowLabel: string) => __TAURI_INVOKE<null>("close_bilibili_login_window", { windowLabel }),
	testDeepseekConnection: (payload: {
	model: string | null,
	baseUrl: string | null,
	apiKey: string | null,
	proxyBypass: boolean | null,
	proxyUrl: string | null,
	proxyMode: string | null,
} | null) => __TAURI_INVOKE<null>("test_deepseek_connection", { payload }),
	searchLogs: (keyword: string, page: number, pageSize: number, level: string | null) => __TAURI_INVOKE<LogSearchResult>("search_logs", { keyword, page, pageSize, level }),
	exportBackup: () => __TAURI_INVOKE<string>("export_backup"),
	importBackup: () => __TAURI_INVOKE<null>("import_backup"),
	/**
	 *  将主窗口隐藏到系统托盘
	 * 
	 *  由前端的 Escape 逐层退出链最后一层触发。仅在用户开启了
	 *  `minimize_to_tray` 设置时才会被调用。
	 */
	hideToTray: () => __TAURI_INVOKE<null>("hide_to_tray"),
	/**
	 *  下载任意 http(s) URL 的原始字节并返回给前端。
	 *  前端复制图片时走 Rust 端下载：绕过 webview CORS 限制，并自动继承应用的代理设置。
	 *  返回 `Vec<u8>`，IPC 序列化为 number[]。
	 */
	fetchUrlBytes: (url: string) => __TAURI_INVOKE<number[]>("fetch_url_bytes", { url }),
	/**
	 *  写入文本到系统剪贴板。
	 *  前端 navigator.clipboard 依赖文档焦点/用户激活，在右键菜单等场景不可靠，
	 *  统一走 Rust 端写入。
	 */
	setClipboardText: (text: string) => __TAURI_INVOKE<null>("set_clipboard_text", { text }),
	/**
	 *  写入图片到系统剪贴板。`bytes` 为 PNG 编码字节（前端已用 canvas 统一转码），
	 *  这里解码为 RGBA 后交给 arboard（由它生成 Windows 需要的 DIBV5/PNG 格式）。
	 */
	setClipboardImage: (bytes: number[]) => __TAURI_INVOKE<null>("set_clipboard_image", { bytes }),
	/**
	 *  批量记录功能按钮点击统计。
	 *  内部校验诊断开关（enable_usage_stats）：关闭时静默丢弃，不做任何写入。
	 */
	recordUsage: (events: ([string, number])[]) => __TAURI_INVOKE<null>("record_usage", { events }),
	/**
	 *  查询使用统计（按累计次数降序）。仅开发者工具调用，不进入任何用户 UI。
	 *  `days` 提供时仅返回最近 N 天的数据（趋势窗口）。
	 */
	getUsageStats: (days: number | null) => __TAURI_INVOKE<UsageStatRow[]>("get_usage_stats", { days }),
	/**  清空全部使用统计。 */
	clearUsageStats: () => __TAURI_INVOKE<null>("clear_usage_stats"),
	/**
	 *  保存全局 Agent 配置。
	 *  进程级字段（agent_type / binary / model / skills）变化时强杀常驻 RPC 进程：
	 *  spawn 只在启动时读一次这些字段，不重启则新配置静默不生效（新增 skill 后 @ 它
	 *  会回到 /skill: 透传失效，改 model 会静默用旧模型）；下次提交 ensure_started 自动
	 *  重启并恢复会话。timeout / prompt_suffix / enabled 每次调度重读，无需重启。
	 */
	saveAgentConfig: (config: AgentConfig) => __TAURI_INVOKE<null>("save_agent_config", { config }),
	/**  读取全局 Agent 配置。 */
	getAgentConfig: () => __TAURI_INVOKE<AgentConfig>("get_agent_config"),
	/**  读取 Agent 工作区面板宽度（逻辑 px；未设置返回 0，前端回退默认 440）。 */
	getAgentWsWidth: () => __TAURI_INVOKE<number>("get_agent_ws_width"),
	/**  保存 Agent 工作区面板宽度（前端拖窗口右边框调节后写入）。 */
	saveAgentWsWidth: (width: number) => __TAURI_INVOKE<null>("save_agent_ws_width", { width }),
	/**
	 *  查询 pi 当前可用模型（scope model）与当前激活模型，供工作区模型下拉。
	 *  惰性拉取：RPC 进程未启动则先启动（常驻进程，后续 run 复用）。
	 *  Agent 未启用时直接返回空（不拉起常驻进程，避免无谓资源占用）。
	 */
	getAgentAvailableModels: () => __TAURI_INVOKE<AgentModelsInfo>("get_agent_available_models"),
	/**
	 *  工作区提交：校验 → 建 run → 后台调度执行，返回 run_id。
	 * 
	 *  - Agent 未启用、skill 未配置、实体无效时拒绝；
	 *  - 会话文件已存在（历史提交）则复用，实现多轮继续；
	 *  - 实际执行在后台任务完成，终态经 `AgentRunFinished` 事件推送。
	 */
	runAgentJob: (input: AgentJobInput) => __TAURI_INVOKE<number>("run_agent_job", { input }),
	/**  查询工作区会话的提交记录（倒序摘要，不含 stdout/stderr 大字段，默认最近 20 条）。 */
	listAgentRuns: (sessionKey: string, limit: number | null) => __TAURI_INVOKE<AgentRunSummary[]>("list_agent_runs", { sessionKey, limit }),
	/**
	 *  查询全局 Agent 队列状态：本会话 pending run 的队列位置 + 其他会话占用情况。
	 *  「排队中」提示的数据源：调度器全局单并发（Semaphore::new(1)），
	 *  本会话 pending 说明有其他 run 占用执行位，前端据此提示「其他会话执行中」。
	 */
	getAgentQueueStatus: (sessionKey: string) => __TAURI_INVOKE<AgentQueueStatus>("get_agent_queue_status", { sessionKey }),
	/**
	 *  读取会话的完整聊天消息流（pi 落盘的 JSONL，leaf 路径，时间正序）。
	 *  会话文件不存在（新会话未提交）→ 空数组；写入中的半行容忍（下轮轮询补齐）。
	 */
	listAgentMessages: (sessionKey: string) => __TAURI_INVOKE<AgentChatMessage[]>("list_agent_messages", { sessionKey }),
	/**
	 *  取消一次正在运行（或排队中）的 Agent 提交。
	 *  「停止」= 向 RPC 常驻进程发 `abort`（不杀进程）：会话上下文保留在进程内存
	 *  与 JSONL 文件，继续对话直接再提交即可，无需恢复流程。
	 *  终态由调度器统一写入（cancelled），本命令不直接写库，避免竞态覆盖。
	 */
	cancelAgentRun: (runId: number) => __TAURI_INVOKE<null>("cancel_agent_run", { runId }),
	/**
	 *  删除一个工作区会话：移除会话文件与全部运行记录。
	 * 
	 *  若该会话存在活跃 run（pending / running），先取消（停止）再删除：
	 *  正在运行的 pi 进程会继续烧 token 直到自然结束或超时，产出写入已删除记录后
	 *  静默丢弃——用户直觉是「删除=停止」，因此删除即停止，避免静默丢产出。
	 *  前端在确认对话框中提示「正在运行，删除将同时停止」。
	 */
	deleteAgentSession: (sessionKey: string) => __TAURI_INVOKE<null>("delete_agent_session", { sessionKey }),
	/**  返回在终端恢复该次会话的命令字符串（供复制）。 */
	getAgentSessionCommand: (runId: number) => __TAURI_INVOKE<string>("get_agent_session_command", { runId }),
	/**  在独立终端窗口中打开该次运行的 pi 会话（`pi --session <path>`），恢复完整执行过程。 */
	openAgentSession: (runId: number) => __TAURI_INVOKE<null>("open_agent_session", { runId }),
};

/** Events */
export const events = {
	agentRpcStream: makeEvent<AgentRpcStream>("agent-rpc-stream"),
	agentRunFinished: makeEvent<AgentRunFinished>("agent-run-finished"),
	navigate: makeEvent<Navigate>("navigate"),
	pollCompleted: makeEvent<PollCompleted>("poll-completed"),
	releaseStateChanged: makeEvent<ReleaseStateChanged>("release-state-changed"),
	sourceAutoDisabled: makeEvent<SourceAutoDisabled>("source-auto-disabled"),
};

/* Types */
/**  一条消息中的内容块（前端按 kind 渲染）。 */
export type AgentChatBlock = 
/**  普通文本（用户提问 / 助手回复 / 自定义消息）。 */
{ kind: "text"; text: string } | 
/**  思考过程（assistant thinking 块，默认折叠展示）。 */
{ kind: "thinking"; text: string } | 
/**  工具调用（assistant toolCall 块，默认折叠展示参数）。 */
{ kind: "toolCall"; id: string; name: string; args: string } | 
/**  工具结果（toolResult 消息，默认折叠展示输出）。 */
{ kind: "toolResult"; id: string; tool_name: string; text: string; is_error: boolean } | 
/**  pi 的 bash 执行消息（命令 + 输出 + 退出码）。 */
{ kind: "bash"; command: string; output: string; exit_code: number | null; truncated: boolean };

/**  一条聊天消息（时间正序，树取当前 leaf 路径）。 */
export type AgentChatMessage = {
	/**  user | assistant | tool | bash | custom */
	role: string,
	blocks: AgentChatBlock[],
	/**  ISO 时间戳（entry 级别，非 message 内嵌）。 */
	timestamp: string,
	/**  生成该消息的模型（仅 assistant）。 */
	model: string | null,
};

/**  全局 Agent 配置（设置页「Agent」分区读写）。 */
export type AgentConfig = {
	/**  总开关：关闭时唤起按钮隐藏，运行命令拒绝执行。 */
	enabled: boolean,
	/**  Agent 类型（"pi" = 本地 pi CLI；新类型在 agent::executor_for 登记）。 */
	agent_type: string,
	/**  Agent 可执行文件显式路径（None = 按类型自动探测，如 where/which pi）。 */
	binary: string | null,
	/**  模型（None = 该 Agent 默认模型）。 */
	model: string | null,
	/**
	 *  Agent 进程工作目录（None = 继承 relwatch 进程 cwd；配置后 pi 的 bash 工具
	 *  默认在该目录运行，避免打包后落在安装目录/项目根）。
	 */
	working_dir: string | null,
	/**  追加在每次提交 prompt 末尾的固定后缀（如"请输出中文"）。 */
	prompt_suffix: string | null,
	/**  子进程超时秒数（超时 kill）。 */
	timeout_seconds: number,
	/**  全局 skill 备选列表（`@` 菜单数据源；运行前校验存在性）。 */
	skills: string[],
};

/**  一次工作区提交引用的实体（拖拽 / `[[]]` 引用统一入口）。 */
export type AgentEntityRef = {
	/**  "source" | "release" */
	kind: string,
	id: number,
};

/**  工作区提交的完整输入。 */
export type AgentJobInput = {
	/**  工作区会话标识（前端 UUID）。同会话多次提交共享 pi 会话文件（多轮继续）。 */
	session_key: string,
	/**  本次提交引用的实体（拖拽 / `[[]]` 解析结果）。 */
	entities: AgentEntityRef[],
	/**  本次提交使用的 skill 路径（`@` 选择；None = 全局列表首个）。 */
	skill_path: string | null,
	/**  用户输入文本（引用已解析剥离）。 */
	instruction: string,
	/**  本次提交显式选择的模型（None = 跟随 pi 当前/默认模型）。 */
	model: AgentModelRef | null,
};

/**
 *  一次提交显式选择的 pi 模型引用（provider + modelId，`set_model` 精确匹配用）。
 *  `agent_runs.model` 列以 JSON 存储；None = 跟随 pi 当前/默认模型（不发送 set_model）。
 */
export type AgentModelRef = {
	/**  pi 模型提供方（如 "anthropic" / "opencode-go"）。 */
	provider: string,
	/**
	 *  模型 id（如 "deepseek-v4-flash"；注意 id 可能自带 provider 前缀如 "cline-pass/..."，
	 *  因此必须拆 provider/modelId 两字段，不能用 `provider/id` 拼接做键）。
	 */
	model_id: string,
};

/**  工作区可选模型信息：pi 当前可用模型列表 + 当前激活模型（「默认」选项实际落点）。 */
export type AgentModelsInfo = {
	/**  scope model：pi 已配置鉴权、可直接使用的模型列表。 */
	models: RpcAvailableModel[],
	/**  pi 进程当前激活模型（None = 无模型）。「默认」选项将使用该模型。 */
	current: RpcAvailableModel | null,
};

/**  全局 Agent 队列状态（「排队中」提示的数据源）。 */
export type AgentQueueStatus = {
	/**  本会话最新 pending run 的全局队列位置（1 = 下一个执行；无 pending → None）。 */
	position: number | null,
	/**  是否存在其他会话的 running run（执行位被占用）。 */
	other_running: boolean,
	/**  其他会话 running run 的 session_key（前端可映射为会话标题）。 */
	running_sessions: string[],
};

/**
 *  pi RPC 事件流实时转发（打字机文本 / 工具状态 / 流式 bash 输出）。
 *  `event` 为 pi RPC 协议的原始事件 JSON 序列化字符串（前端 JSON.parse 还原）。
 */
export type AgentRpcStream = {
	session_key: string,
	run_id: number,
	event: string,
};

/**  一次 Agent 提交运行结束（成功/失败/超时/取消），前端据此刷新工作区记录。 */
export type AgentRunFinished = {
	run_id: number,
	/**  所属工作区会话标识（前端按 session_key 过滤刷新）。 */
	session_key: string,
	/**  success | failed | timeout | cancelled */
	status: string,
	/**  失败/超时的人类可读原因（成功时 null）。 */
	message: string | null,
};

/**
 *  一次工作区提交的列表摘要（不含 stdout/stderr 大字段，供会话记录列表）。
 *  stdout 存的是模型完整输出，列表接口最多拉 100 条，全列返回会拖慢查询与序列化。
 */
export type AgentRunSummary = {
	id: number,
	session_key: string,
	skill_path: string | null,
	entities: string,
	instruction: string,
	model: string | null,
	session_path: string | null,
	status: string,
	exit_code: number | null,
	error: string | null,
	started_at: string | null,
	finished_at: string | null,
	created_at: string,
};

/**
 *  设置读写共用同一结构：get_settings 返回它，update_settings 直接接收它。
 *  前端 payload 与后端结构字段一一对应（snake_case），
 *  新增设置项只需改 AppSettings 一处 + get_settings/apply_settings 两处。
 */
export type AppSettings = {
	poll_interval_minutes: number,
	proxy_url: string,
	proxy_mode: string,
	auto_start: boolean,
	minimize_to_tray: boolean,
	log_retention_days: number,
	deepseek_enabled: boolean,
	deepseek_model: string,
	deepseek_base_url: string,
	/**  派生只读标志（凭据是否已设置），update_settings 忽略其值。 */
	deepseek_api_key_set: boolean,
	deepseek_proxy_bypass: boolean,
	deepseek_prompt: string,
	deepseek_min_importance: string,
	deepseek_translate_release: boolean,
	check_prereleases: boolean,
	fetch_history: boolean,
	fetch_history_count: number,
	language: string,
	theme: string,
	show_source_type_icons: boolean,
	enable_usage_stats: boolean,
	github_token_set: boolean,
	youtube_api_key_set: boolean,
	bilibili_cookie_set: boolean,
};

export type LogEntry = {
	id: number,
	level: string,
	message: string,
	created_at: string,
	message_key: string | null,
	message_args: string | null,
	rendered_message: string | null,
};

export type LogSearchResult = {
	entries: LogEntry[],
	total: number,
	page: number,
	page_size: number,
};

/**  托盘菜单请求前端切换标签页，payload 为目标标签名。 */
export type Navigate = string;

/**  一次轮询完成（手动或定时），前端据此刷新列表与倒计时。 */
export type PollCompleted = null;

export type PollResult = {
	new_releases: ReleaseInfo[],
};

export type ReleaseInfo = {
	id: number,
	source_id: number,
	source_type: string,
	owner: string,
	repo: string,
	tag_name: string,
	release_name: string,
	html_url: string,
	published_at: string,
	prerelease: boolean,
	body: string | null,
	detected_at: string,
	notification_status: string,
	snooze_until: string | null,
	ai_summary: string | null,
	ai_importance: string | null,
	body_translated: string | null,
	extra_metadata: string | null,
	/**  所属源的描述（YouTube 源存频道名），前端用于展示可读名称。 */
	source_description: string | null,
};

/**  release 状态变更（新增/已读/忽略/删除等），payload 为 release id。 */
export type ReleaseStateChanged = number;

/**
 *  pi 可选模型（scope model：provider 已配置鉴权、可直接使用）。
 *  来自 RPC `get_available_models` / `get_state` 返回的 Model JSON，仅提取前端需要的字段。
 *  注意 id 可能自带 provider 前缀（如 `cline-pass/deepseek-v4-flash`），
 *  因此 `set_model` 必须用 provider + modelId 双字段精确匹配。
 */
export type RpcAvailableModel = {
	provider: string,
	id: string,
	name?: string | null,
};

export type Source = {
	id: number,
	source_type: string,
	owner: string,
	repo: string,
	poll_interval_minutes: number,
	enabled: boolean,
	last_checked_at: string | null,
	last_check_status: string,
	last_check_message: string | null,
	consecutive_failures: number,
	last_new_count: number,
	muted: boolean,
	created_at: string,
	updated_at: string,
	description: string | null,
	/**  源级附加配置（JSON）。目前用于 YouTube 订阅内容类型（视频/直播/帖子）。 */
	config: string | null,
};

/**  源因连续失败被自动禁用，payload 携带源信息供前端提示。 */
export type SourceAutoDisabled = {
	owner: string,
	repo: string,
	id: number,
	failures: number,
};

/**
 *  源类型的能力元数据：由 `ADAPTERS` 注册表动态枚举，供前端注册表对拍/展示。
 *  新增源类型只需在 source.rs::ADAPTERS 登记，本命令自动下发。
 */
export type SourceTypeInfo = {
	/**  与后端 source_type 一致的标识（如 "github"）。 */
	source_type: string,
	/**  鉴权方式标识（none / github_token / youtube_api_key / bilibili_cookie）。 */
	auth_kind: string,
	/**  是否参与 AI 摘要/翻译（对应前端 SourceTypeDef.aiSummary）。 */
	ai_eligible: boolean,
	/**  是否每次检查都按 fetch_history_count 拉历史。 */
	always_fetch_history: boolean,
	/**  检查成功后是否刷新 description。 */
	refresh_description_after_check: boolean,
};

/**
 *  测试连接的可选覆盖参数：前端把表单当前值（含未保存修改）传入，
 *  留空的项回退到已保存配置，实现"先试后存"。
 */
export type TestDeepseekPayload = {
	model: string | null,
	baseUrl: string | null,
	apiKey: string | null,
	proxyBypass: boolean | null,
	proxyUrl: string | null,
	proxyMode: string | null,
};

/**  单日计数（按本地时区 YYYY-MM-DD 分桶）。 */
export type UsageDaily = {
	day: string,
	count: number,
};

/**  单个事件的聚合统计行：total_count 为累计次数（SUM），daily 为按天趋势。 */
export type UsageStatRow = {
	key: string,
	total_count: number,
	last_day: string,
	daily: UsageDaily[],
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

